# Generated by Django 5.0.7 on 2024-08-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="Zip",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
    ]
